kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-hp001
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
